### Create User
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Karina",
    "username": "karina",
    "email": "admin2@gmail.com",
    "password": "admin",
    "role": "EDITOR"
}


### login 
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin" 
}


### Update User
PATCH http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiTmluZyBOaW5nIiwidXNlcm5hbWUiOiJuaW5nIG5pbmciLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsInByb2ZpbGVJbWFnZSI6ImJsYWNraG9sZWY3ZDAxMDRlLWFhZGUtNDllYy05ZTJmLWNjOTZlNGM2ZDRjNy5qcGcifSwiaWF0IjoxNjUxNDk4MTQ0LCJleHAiOjE2NTE1MDgxNDR9.7C28dhsxirKwRbPzpXz2sdi2VDHDLztcwn3MglURG-0

{
    "name": "Ning Ning",
    "username": "ning ning",
    "email": "ning@gmail.com"
}


### Update Role
PATCH http://localhost:3000/users/1/update-role
Content-Type: application/json

{
    "role": "EDITOR"
}


### Find by id
GET http://localhost:3000/users/7


### find all 
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiTmluZyBOaW5nIiwidXNlcm5hbWUiOiJuaW5nIG5pbmciLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsInByb2ZpbGVJbWFnZSI6ImJsYWNraG9sZWY3ZDAxMDRlLWFhZGUtNDllYy05ZTJmLWNjOTZlNGM2ZDRjNy5qcGcifSwiaWF0IjoxNjUxNDk4MTQ0LCJleHAiOjE2NTE1MDgxNDR9.7C28dhsxirKwRbPzpXz2sdi2VDHDLztcwn3MglURG-0


### find all by using page & limit
GET http://localhost:3000/users?page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiTGlseSIsInVzZXJuYW1lIjoibGlseSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwicHJvZmlsZUltYWdlIjpudWxsfSwiaWF0IjoxNjUxNDgzMTEyLCJleHAiOjE2NTE0OTMxMTJ9.l1w4Y6-pLQl5P3Juwk7VUAUd_X6fxWnNlFGXnm9tS4E

### find all by using page & limit & username (always use page=0)
GET http://localhost:3000/users?username=karina&page=0&limit=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiTGlseSIsInVzZXJuYW1lIjoibGlseSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwicHJvZmlsZUltYWdlIjpudWxsfSwiaWF0IjoxNjUxNDgzMTEyLCJleHAiOjE2NTE0OTMxMTJ9.l1w4Y6-pLQl5P3Juwk7VUAUd_X6fxWnNlFGXnm9tS4E

### delete by id
DELETE  http://localhost:3000/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiTGlseSIsInVzZXJuYW1lIjoibGlseSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwicHJvZmlsZUltYWdlIjpudWxsfSwiaWF0IjoxNjUxNDgzMjY3LCJleHAiOjE2NTE0OTMyNjd9.zlo9jb9NuQlHULkcHA7A3f83bQRT-mghX-A-nIYZcs0
 

### Upload file (Test with postman - use body > form-data > File)
POST http://localhost:3000/users/upload


### find Profile Image
GET http://localhost:3000/users/profile-image/blackholef7d0104e-aade-49ec-9e2f-cc96e4c6d4c7.jpg
    